#可以通过命令调用不同的环境
spring:
  profiles:
    #配置当前的环境：开发环境还是生产环境dev、prod
    active: dev
  main:
    banner-mode: console
  mvc:
    #页面图标favicon
    favicon:
      enabled: true
  application:
    name: spring-boot-mybatis-plus
